services:
  - type: web
    name: smartcropx-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: ALLOWED_ORIGINS
        value: https://smartcropx-app.onrender.com,http://localhost:3000
    healthCheckPath: /health
    autoDeploy: true